# Generated by Django 2.1 on 2020-09-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200923_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
