# Generated by Django 2.2.7 on 2020-09-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('shelter_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('shelter_name', models.CharField(max_length=128)),
                ('shelter_address', models.CharField(max_length=300)),
                ('shelter_tel', models.CharField(max_length=20)),
                ('charge_name', models.CharField(max_length=300)),
                ('shelter_lat', models.CharField(max_length=128)),
                ('shelter_lng', models.CharField(max_length=128)),
            ],
        ),
    ]
