# Generated by Django 2.1 on 2020-09-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='dog_id',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
